version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: university-minio
    ports:
      - "9000:9000" # Порт для API (К нему подключается Java и фронтенд)
      - "9001:9001" # Порт для красивого Web UI (Консоль администратора)
    environment:
      MINIO_ROOT_USER: admin_access_key
      MINIO_ROOT_PASSWORD: admin_secret_key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Сохраняем файлы на жестком диске даже после рестарта докера
    restart: unless-stopped

  # Контейнер-инициализатор. Выполнит скрипт и завершит работу.
  minio-init:
    image: minio/mc:latest
    container_name: university-minio-init
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Ожидание запуска MinIO..."
        while ! mc alias set myminio http://minio:9000 admin_access_key admin_secret_key; do
          echo "MinIO еще не готов, ждем 2 секунды..."
          sleep 2
        done
        
        echo "MinIO запущен. Создание бакетов..."
        mc mb myminio/university-public || true
        mc mb myminio/university-private || true
        
        echo "Настройка политик доступа..."
        mc anonymous set download myminio/university-public
        
        echo "Инициализация завершена!"
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      # Настройки для официального образа Apache Kafka (используется префикс KAFKA_)
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # Привязка адресов
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      # Обязательные настройки для локального запуска в 1 ноду, чтобы избежать ошибок репликации
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      # В официальном образе скрипты лежат в /opt/kafka/bin/
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for Kafka to be ready...' &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic my-custom-topic --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1 &&
        echo 'Topic created successfully!'
      "
    restart: "no"

volumes:
  minio_data: