spring:
  application:
    name: file-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DB_USERNAME:users}
    password: ${DB_PASSWORD:users}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/files-changelog-master.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    admin:
      auto-create: false
    consumer:
      group-id: "files-consumer-group"
      auto-offset-reset: earliest

file-consumer:
  file-event-topic-name: my-custom-topic
  delay-between-retries: 1000
  file-deleted-event-name: "file_deleted_event"
  file-loaded-event-name: "file_loaded_event"
  max-attempts: 5
  type-header-name: "type_id"

s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  region: ${S3_REGION:us-east-1}
  access-key: ${S3_ACCESS_KEY:admin_access_key}
  secret-key: ${S3_SECRET_KEY:admin_secret_key}
  public-bucket: ${S3_PUBLIC_BUCKET:university-public}
  private-bucket: ${S3_PRIVATE_BUCKET:university-private}
server:
  port: ${SERVER_PORT:8087}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: TRACE
    org.springframework.web.HttpLogging: DEBUG
    org.apache.catalina.core.ContainerBase: DEBUG